### ISSUE TITLE
What happens if I have different color schemes for different syntaxes?

### ISSUE THREAD

**Issue by mandx** [pradyunsg/Sublime-Rainbow-Theme#3]
(I can't test this myself because of #2 )

In my setup I have one color scheme for everything, but I use a different one for Python (because it highlights keywords better, plays better with MagicPython, etc).

Will this plugin change the theme on the fly as I change tabs? Will it use only the global setting?

**Comment by pradyunsg** [comment]
> Will this plugin change the theme on the fly as I change tabs?

It will if the setting `load_colors_from_active_view` in `Theme - Rainbow.sublime-settings` is true (which it is by default). If you wish to use the global setting, set the said variable to false.
