### ISSUE TITLE
Pure default adaptive theme

### ISSUE THREAD

**Issue by ghost** [pradyunsg/Sublime-Rainbow-Theme#8]
It would be cool if the rainbow theme has an option to not touch anything else in the ui like changing tabs, folders, icons etc. and just used the default sublime text ui while being adaptive to the used syntax theme.

**Comment by pradyunsg** [comment]
That's a wonderful idea!

It's quite doable except I don't really have the time to put into this project as on today. I'll keep it open if someone comes by and feels like taking this on.

**Comment by ghost** [comment]
I think we should close this my fellow. The dev build 3127 of sublime text implemented an adaptive theme I see.

**Comment by pradyunsg** [comment]
Yep!
